/* Copyright (C) 2023 Eccelerators GmbH
   
   This code was generated by:
  
   HxS Compiler 1.0.19-10671667
   C Extension for HxS 1.0.24-85d98215
   
   Further information at https://eccelerators.com/hxs
   
   Changes to this file may cause incorrect behavior and will be lost if the
   code is regenerated.
*/	
	
#ifndef _InterruptGeneratorIfc_H
#define _InterruptGeneratorIfc_H

/* ----------------------------------------------------- */
/* Addresses, widths, values and masks for direct access */
/* ----------------------------------------------------- */
#define InterruptGeneratorIfcAddressBusWidth 16
#define InterruptGeneratorIfcDataBusWidth 32

#define InterruptGeneratorBlkAddress 0x0000
#define InterruptGeneratorBlkSize 0x0054

#define ControlRegAddress (0x0000 + InterruptGeneratorBlkAddress)
#define ControlRegWidth 4

#define ControlReg_ChannelOperation0Mask 0x8
#define ControlReg_ChannelOperation0Position 3
#define ControlReg_ChannelOperation0Width 1
#define ControlReg_ChannelOperation0_EnabledMVal 0x8
#define ControlReg_ChannelOperation0_DisabledMVal 0x0
#define ControlReg_ChannelOperation0BusResetMRstVal 0x0

#define ControlReg_ChannelOperation1Mask 0x4
#define ControlReg_ChannelOperation1Position 2
#define ControlReg_ChannelOperation1Width 1
#define ControlReg_ChannelOperation1_EnabledMVal 0x4
#define ControlReg_ChannelOperation1_DisabledMVal 0x0
#define ControlReg_ChannelOperation1BusResetMRstVal 0x0

#define ControlReg_ChannelOperation2Mask 0x2
#define ControlReg_ChannelOperation2Position 1
#define ControlReg_ChannelOperation2Width 1
#define ControlReg_ChannelOperation2_EnabledMVal 0x2
#define ControlReg_ChannelOperation2_DisabledMVal 0x0
#define ControlReg_ChannelOperation2BusResetMRstVal 0x0

#define ControlReg_ChannelOperation3Mask 0x1
#define ControlReg_ChannelOperation3Position 0
#define ControlReg_ChannelOperation3Width 1
#define ControlReg_ChannelOperation3_EnabledMVal 0x1
#define ControlReg_ChannelOperation3_DisabledMVal 0x0
#define ControlReg_ChannelOperation3BusResetMRstVal 0x0

#define StatusRegAddress (0x0000 + InterruptGeneratorBlkAddress)
#define StatusRegWidth 4

#define StatusReg_ChannelStatus0Mask 0xC0
#define StatusReg_ChannelStatus0Position 6
#define StatusReg_ChannelStatus0Width 2
#define StatusReg_ChannelStatus0_IdleMVal 0x0
#define StatusReg_ChannelStatus0_OperatingMVal 0x40
#define StatusReg_ChannelStatus0_EndedMValAMask 0x80
#define StatusReg_ChannelStatus0_EndedMValListSize 2
#define StatusReg_ChannelStatus0_EndedMValList { \
    0x80, 0xC0};

#define StatusReg_ChannelStatus1Mask 0x30
#define StatusReg_ChannelStatus1Position 4
#define StatusReg_ChannelStatus1Width 2
#define StatusReg_ChannelStatus1_IdleMVal 0x0
#define StatusReg_ChannelStatus1_OperatingMVal 0x10
#define StatusReg_ChannelStatus1_EndedMValAMask 0x20
#define StatusReg_ChannelStatus1_EndedMValListSize 2
#define StatusReg_ChannelStatus1_EndedMValList { \
    0x20, 0x30};

#define StatusReg_ChannelStatus2Mask 0xC
#define StatusReg_ChannelStatus2Position 2
#define StatusReg_ChannelStatus2Width 2
#define StatusReg_ChannelStatus2_IdleMVal 0x0
#define StatusReg_ChannelStatus2_OperatingMVal 0x4
#define StatusReg_ChannelStatus2_EndedMValAMask 0x8
#define StatusReg_ChannelStatus2_EndedMValListSize 2
#define StatusReg_ChannelStatus2_EndedMValList { \
    0x8, 0xC};

#define StatusReg_ChannelStatus3Mask 0x3
#define StatusReg_ChannelStatus3Position 0
#define StatusReg_ChannelStatus3Width 2
#define StatusReg_ChannelStatus3_IdleMVal 0x0
#define StatusReg_ChannelStatus3_OperatingMVal 0x1
#define StatusReg_ChannelStatus3_EndedMValAMask 0x2
#define StatusReg_ChannelStatus3_EndedMValListSize 2
#define StatusReg_ChannelStatus3_EndedMValList { \
    0x2, 0x3};

#define ChargedCountReg0Address (0x0000 + InterruptGeneratorBlkAddress)
#define ChargedCountReg0Width 32

#define ChargedCountReg0_CountMask 0xFFFFFFFF
#define ChargedCountReg0_CountPosition 0
#define ChargedCountReg0_CountWidth 32
#define ChargedCountReg0_CountBusResetMRstVal 0x00000000

#define ChargedCountReg1Address (0x0004 + InterruptGeneratorBlkAddress)
#define ChargedCountReg1Width 32

#define ChargedCountReg1_CountMask 0xFFFFFFFF
#define ChargedCountReg1_CountPosition 0
#define ChargedCountReg1_CountWidth 32
#define ChargedCountReg1_CountBusResetMRstVal 0x00000000

#define ChargedCountReg2Address (0x0008 + InterruptGeneratorBlkAddress)
#define ChargedCountReg2Width 32

#define ChargedCountReg2_CountMask 0xFFFFFFFF
#define ChargedCountReg2_CountPosition 0
#define ChargedCountReg2_CountWidth 32
#define ChargedCountReg2_CountBusResetMRstVal 0x00000000

#define ChargedCountReg3Address (0x000C + InterruptGeneratorBlkAddress)
#define ChargedCountReg3Width 32

#define ChargedCountReg3_CountMask 0xFFFFFFFF
#define ChargedCountReg3_CountPosition 0
#define ChargedCountReg3_CountWidth 32
#define ChargedCountReg3_CountBusResetMRstVal 0x00000000

#define ActualCountReg0Address (0x0010 + InterruptGeneratorBlkAddress)
#define ActualCountReg0Width 32

#define ActualCountReg0_CountMask 0xFFFFFFFF
#define ActualCountReg0_CountPosition 0
#define ActualCountReg0_CountWidth 32

#define ActualCountReg1Address (0x0014 + InterruptGeneratorBlkAddress)
#define ActualCountReg1Width 32

#define ActualCountReg1_CountMask 0xFFFFFFFF
#define ActualCountReg1_CountPosition 0
#define ActualCountReg1_CountWidth 32

#define ActualCountReg2Address (0x0018 + InterruptGeneratorBlkAddress)
#define ActualCountReg2Width 32

#define ActualCountReg2_CountMask 0xFFFFFFFF
#define ActualCountReg2_CountPosition 0
#define ActualCountReg2_CountWidth 32

#define ActualCountReg3Address (0x001C + InterruptGeneratorBlkAddress)
#define ActualCountReg3Width 32

#define ActualCountReg3_CountMask 0xFFFFFFFF
#define ActualCountReg3_CountPosition 0
#define ActualCountReg3_CountWidth 32

#define FailureCountReg0Address (0x0020 + InterruptGeneratorBlkAddress)
#define FailureCountReg0Width 32

#define FailureCountReg0_CountMask 0xFFFFFFFF
#define FailureCountReg0_CountPosition 0
#define FailureCountReg0_CountWidth 32

#define FailureCountReg1Address (0x0024 + InterruptGeneratorBlkAddress)
#define FailureCountReg1Width 32

#define FailureCountReg1_CountMask 0xFFFFFFFF
#define FailureCountReg1_CountPosition 0
#define FailureCountReg1_CountWidth 32

#define FailureCountReg2Address (0x0028 + InterruptGeneratorBlkAddress)
#define FailureCountReg2Width 32

#define FailureCountReg2_CountMask 0xFFFFFFFF
#define FailureCountReg2_CountPosition 0
#define FailureCountReg2_CountWidth 32

#define FailureCountReg3Address (0x002C + InterruptGeneratorBlkAddress)
#define FailureCountReg3Width 32

#define FailureCountReg3_CountMask 0xFFFFFFFF
#define FailureCountReg3_CountPosition 0
#define FailureCountReg3_CountWidth 32

#define IntervalReg0Address (0x0030 + InterruptGeneratorBlkAddress)
#define IntervalReg0Width 32

#define IntervalReg0_IntervalMask 0xFFFFFFFF
#define IntervalReg0_IntervalPosition 0
#define IntervalReg0_IntervalWidth 32
#define IntervalReg0_IntervalBusResetMRstVal 0x00000000

#define IntervalReg1Address (0x0034 + InterruptGeneratorBlkAddress)
#define IntervalReg1Width 32

#define IntervalReg1_IntervalMask 0xFFFFFFFF
#define IntervalReg1_IntervalPosition 0
#define IntervalReg1_IntervalWidth 32
#define IntervalReg1_IntervalBusResetMRstVal 0x00000000

#define IntervalReg2Address (0x0038 + InterruptGeneratorBlkAddress)
#define IntervalReg2Width 32

#define IntervalReg2_IntervalMask 0xFFFFFFFF
#define IntervalReg2_IntervalPosition 0
#define IntervalReg2_IntervalWidth 32
#define IntervalReg2_IntervalBusResetMRstVal 0x00000000

#define IntervalReg3Address (0x003C + InterruptGeneratorBlkAddress)
#define IntervalReg3Width 32

#define IntervalReg3_IntervalMask 0xFFFFFFFF
#define IntervalReg3_IntervalPosition 0
#define IntervalReg3_IntervalWidth 32
#define IntervalReg3_IntervalBusResetMRstVal 0x00000000

#define ReferenceCountReg0Address (0x0040 + InterruptGeneratorBlkAddress)
#define ReferenceCountReg0Width 32

#define ReferenceCountReg0_CountMask 0xFFFFFFFF
#define ReferenceCountReg0_CountPosition 0
#define ReferenceCountReg0_CountWidth 32
#define ReferenceCountReg0_CountBusResetMRstVal 0x00000000

#define ReferenceCountReg1Address (0x0044 + InterruptGeneratorBlkAddress)
#define ReferenceCountReg1Width 32

#define ReferenceCountReg1_CountMask 0xFFFFFFFF
#define ReferenceCountReg1_CountPosition 0
#define ReferenceCountReg1_CountWidth 32
#define ReferenceCountReg1_CountBusResetMRstVal 0x00000000

#define ReferenceCountReg2Address (0x0048 + InterruptGeneratorBlkAddress)
#define ReferenceCountReg2Width 32

#define ReferenceCountReg2_CountMask 0xFFFFFFFF
#define ReferenceCountReg2_CountPosition 0
#define ReferenceCountReg2_CountWidth 32
#define ReferenceCountReg2_CountBusResetMRstVal 0x00000000

#define ReferenceCountReg3Address (0x004C + InterruptGeneratorBlkAddress)
#define ReferenceCountReg3Width 32

#define ReferenceCountReg3_CountMask 0xFFFFFFFF
#define ReferenceCountReg3_CountPosition 0
#define ReferenceCountReg3_CountWidth 32
#define ReferenceCountReg3_CountBusResetMRstVal 0x00000000

#endif
